/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LasquetiSpice (https://sketchfab.com/LasquetiSpice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-astronaut-in-space-suit-loop-137d62cd820a4a6eba75304a11fb6f81
Title: Animated Astronaut in Space Suit Loop
*/
"use client";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Wizard(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/scene-transformed.glb"
  );

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  const { actions } = useAnimations(animations, group);
  return (
    <group
      ref={modelRef}
      {...props}
      dispose={null}
      position={[0, -1.5, 0]}
      scale={[1, 1, 1]}
      rotation={[0.25, 0, 0]}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_102"
          geometry={nodes.Object_102.geometry}
          material={materials.material0}
          skeleton={nodes.Object_102.skeleton}
          scale={0.013}
        />
        <skinnedMesh
          name="Object_103"
          geometry={nodes.Object_103.geometry}
          material={materials.material0}
          skeleton={nodes.Object_103.skeleton}
          scale={0.013}
        />
        <skinnedMesh
          name="Object_106"
          geometry={nodes.Object_106.geometry}
          material={materials.material1}
          skeleton={nodes.Object_106.skeleton}
          scale={0.013}
        />
        <skinnedMesh
          name="Object_109"
          geometry={nodes.Object_109.geometry}
          material={materials.material2}
          skeleton={nodes.Object_109.skeleton}
          scale={0.013}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/scene-transformed.glb");
